# The size of the gui. Must be
# between 9 and 54 and must be a multiple of 9.
slots: 54

layout:

  # The slots that display the station's recipes.
  recipe-slots: [12, 13, 14, 15, 21, 22, 23, 24, 30, 31, 32, 33]

  # The slots that display the station's queue slots.
  queue-slots: [47, 48, 49, 50, 51]

  # The slots that display the arrows to navigate
  # the station's recipes.
  # Only shows when it can be used.
  recipe-previous-slot: 20

  recipe-next-slot: 25

  # The slots that display the arrows to navigate
  # the station's queue.
  # Only shows when it can be used.
  queue-previous-slot: 37

  queue-next-slot: 43