# 自动生成的物品配置文件
info:
  namespace: cw_armor2
equipments:
  warrior:
    type: armor
    layer_1: armor/warrior/layer_1
    layer_2: armor/warrior/layer_2
items:
  warrior_boots:
    name: warrior_boots
    resource:
      generate: true
      texture: items/warrior/boots.png
      material: NETHERITE_boots
    equipment:
      id: cw_armor2:warrior
  warrior_chestplate:
    name: warrior_chestplate
    resource:
      generate: true
      texture: items/warrior/chestplate.png
      material: NETHERITE_chestplate
    equipment:
      id: cw_armor2:warrior
  warrior_helmet:
    name: warrior_helmet
    resource:
      generate: true
      texture: items/warrior/helmet.png
      material: NETHERITE_helmet
    equipment:
      id: cw_armor2:warrior
  warrior_leggings:
    name: warrior_leggings
    resource:
      generate: true
      texture: items/warrior/leggings.png
      material: NETHERITE_leggings
    equipment:
      id: cw_armor2:warrior
