# 自动生成的物品配置文件
info:
  namespace: cw_armor2
equipments:
  necromancer:
    type: armor
    layer_1: armor/necromancer/layer_1
    layer_2: armor/necromancer/layer_2
items:
  necromancer_boots:
    name: necromancer_boots
    resource:
      generate: true
      texture: items/necromancer/boots.png
      material: NETHERITE_boots
    equipment:
      id: cw_armor2:necromancer
  necromancer_chestplate:
    name: necromancer_chestplate
    resource:
      generate: true
      texture: items/necromancer/chestplate.png
      material: NETHERITE_chestplate
    equipment:
      id: cw_armor2:necromancer
  necromancer_helmet:
    name: necromancer_helmet
    resource:
      generate: true
      texture: items/necromancer/helmet.png
      material: NETHERITE_helmet
    equipment:
      id: cw_armor2:necromancer
  necromancer_leggings:
    name: necromancer_leggings
    resource:
      generate: true
      texture: items/necromancer/leggings.png
      material: NETHERITE_leggings
    equipment:
      id: cw_armor2:necromancer
