# 自动生成的分类配置文件
info:
  namespace: cw_items
categories:
  coin:
    enabled: true
    icon: cw_items:c_0
    name: coin
    items:
    - cw_items:c_0
    - cw_items:c_1
    - cw_items:c_2
    - cw_items:c_3
    - cw_items:c_slime_0
    - cw_items:c_slime_1
    - cw_items:c_slime_2
    - cw_items:c_slime_3
    - cw_items:rabbit0
    - cw_items:rabbit1
    - cw_items:rabbit2
    - cw_items:rabbit3
    - cw_items:rabbit4
    - cw_items:rabbit5
    - cw_items:sou1
    - cw_items:soul2
    - cw_items:soul3
    - cw_items:soul4
    - cw_items:soul5
    - cw_items:soul6
  drop:
    enabled: true
    icon: cw_items:amber
    name: drop
    items:
    - cw_items:amber
    - cw_items:amethyst_gemcorn
    - cw_items:ancient_cloth
    - cw_items:ancient_horn
    - cw_items:antlion_mandible
    - cw_items:beetle_husk
    - cw_items:bee_wax
    - cw_items:bestiary_the_crimson
    - cw_items:black_fairy_dust
    - cw_items:black_lens
    - cw_items:black_thread
    - cw_items:bloody_tear
    - cw_items:bone_feather
    - cw_items:bone_key
    - cw_items:brain
    - cw_items:broken_hero_sword
    - cw_items:butterfly_dust
    - cw_items:cactus
    - cw_items:coral
    - cw_items:corruption_key
    - cw_items:corruption_key_mold
    - cw_items:cream_soda
    - cw_items:crimson_heart
    - cw_items:crimson_key
    - cw_items:crimson_key_mold
    - cw_items:crystal_shard
    - cw_items:cursed_flame
    - cw_items:cyan_dye
    - cw_items:cyan_husk
    - cw_items:dark_shard
    - cw_items:deathweed
    - cw_items:desert_key
    - cw_items:desert_spirit_lamp
    - cw_items:djinn_curse
    - cw_items:dungeon_spirit
    - cw_items:dye_black
    - cw_items:dye_blue
    - cw_items:dye_brown
    - cw_items:dye_green
    - cw_items:dye_orange
    - cw_items:dye_pink
    - cw_items:dye_red
    - cw_items:dye_silver
    - cw_items:dye_teal
    - cw_items:dye_yellow
    - cw_items:ectoplasm
    - cw_items:empty_bullet
    - cw_items:empty_dropper
    - cw_items:explosive_powder
    - cw_items:fairy_bell
    - cw_items:fallen_star
    - cw_items:feather
    - cw_items:fire_feather
    - cw_items:flinx_fur
    - cw_items:fragment_forbidden
    - cw_items:fragment_nebula
    - cw_items:fragment_solar
    - cw_items:fragment_stardust
    - cw_items:fragment_vortex
    - cw_items:fried_egg
    - cw_items:frost_core
    - cw_items:frozen_key
    - cw_items:frozen_key_mold
    - cw_items:frozen_turtle_shell
    - cw_items:gel
    - cw_items:gelatin_crystal
    - cw_items:gem1
    - cw_items:gem2
    - cw_items:gem3
    - cw_items:gem4
    - cw_items:gem5
    - cw_items:giant_cursed_skull
    - cw_items:giant_harpy_feather
    - cw_items:glowing_mushroom
    - cw_items:gmk
    - cw_items:goat_skull
    - cw_items:golden_key
    - cw_items:gold_dust
    - cw_items:gold_squirrel
    - cw_items:green_mushroom
    - cw_items:green_thread
    - cw_items:hallowed_key
    - cw_items:hallowed_key_mold
    - cw_items:hell_butterfly
    - cw_items:ice_feather
    - cw_items:jungle_key
    - cw_items:jungle_key_mold
    - cw_items:jungle_spores
    - cw_items:king_slime_mask
    - cw_items:large_amethyst
    - cw_items:lavafly
    - cw_items:lchor
    - cw_items:lemon
    - cw_items:lens
    - cw_items:lightning_bug
    - cw_items:light_shard
    - cw_items:living_cursed_fire
    - cw_items:living_demon_fire
    - cw_items:living_fire_block
    - cw_items:living_frost_fire
    - cw_items:living_ichor
    - cw_items:lizard_egg
    - cw_items:magic_honey_dropper
    - cw_items:magic_lava_dropper
    - cw_items:magic_sand_dropper
    - cw_items:magic_water_dropper
    - cw_items:monster_meat
    - cw_items:moon_leech_clot
    - cw_items:nanites
    - cw_items:nb_copper
    - cw_items:orange_bloodroot
    - cw_items:ornate_shadow_key
    - cw_items:pearl_black
    - cw_items:pearl_galaxy
    - cw_items:pearl_pink
    - cw_items:pearl_white
    - cw_items:pink_gel
    - cw_items:pink_thread
    - cw_items:pixie_dust
    - cw_items:purple_thread
    - cw_items:queen_slime_mask
    - cw_items:regal_delicacy
    - cw_items:reinforced_echo_shard
    - cw_items:rxj
    - cw_items:seaweed
    - cw_items:seedling
    - cw_items:shadow_key
    - cw_items:shadow_orb
    - cw_items:shark_fin
    - cw_items:shark_kite
    - cw_items:silk
    - cw_items:sky_blue_flower
    - cw_items:slice_of_hell_cake
    - cw_items:smg
    - cw_items:solar_tablet
    - cw_items:spooky_twig
    - cw_items:stinger
    - cw_items:strange_glowing_mushroom
    - cw_items:sturdy_fossil
    - cw_items:sunflower
    - cw_items:suspicious_looking_eye
    - cw_items:tattered_cloth
    - cw_items:teal_mushroom
    - cw_items:tissue_sample
    - cw_items:treasure_bag_betsy
    - cw_items:treasure_bag_brain_of_cthulhu
    - cw_items:treasure_bag_dark_mage
    - cw_items:treasure_bag_deerclops
    - cw_items:treasure_bag_duke_fishron
    - cw_items:treasure_bag_eater_of_worlds
    - cw_items:treasure_bag_empress_of_light
    - cw_items:treasure_bag_eye_of_cthulhu
    - cw_items:treasure_bag_golem
    - cw_items:treasure_bag_king_slime
    - cw_items:treasure_bag_lunatic_cultist
    - cw_items:treasure_bag_noon_kord
    - cw_items:treasure_bag_ogre
    - cw_items:treasure_bag_plantera
    - cw_items:treasure_bag_queen_bee
    - cw_items:treasure_bag_queen_slime
    - cw_items:treasure_bag_skeletron
    - cw_items:treasure_bag_skeletron_prime
    - cw_items:treasure_bag_the_destroyer
    - cw_items:treasure_bag_the_twins
    - cw_items:treasure_bag_wall_of_flesh
    - cw_items:truffle_worm
    - cw_items:turtle_shell
    - cw_items:vertebra
    - cw_items:vicious_mushroom
    - cw_items:vile_mushroom
    - cw_items:vine
    - cw_items:violet_husk
    - cw_items:wolf_fang
    - cw_items:wu_stick
  icon:
    enabled: true
    icon: cw_items:air
    name: icon
    items:
    - cw_items:air
    - cw_items:auction111
    - cw_items:auction222
    - cw_items:back
    - cw_items:bought
    - cw_items:builder_select
    - cw_items:cancel
    - cw_items:category
    - cw_items:cha
    - cw_items:check
    - cw_items:clear
    - cw_items:coin1
    - cw_items:confirm
    - cw_items:cross
    - cw_items:crystal
    - cw_items:cw_kill
    - cw_items:cw_level
    - cw_items:cw_level_xp
    - cw_items:cw_money
    - cw_items:cw_point
    - cw_items:cw_point_pro
    - cw_items:cw_ui_1
    - cw_items:cw_ui_2
    - cw_items:cw_ui_3
    - cw_items:cw_ui_4
    - cw_items:cw_ui_5
    - cw_items:cw_ui_6
    - cw_items:cw_ui_7
    - cw_items:diamond_cog
    - cw_items:digger_select
    - cw_items:expired
    - cw_items:farmer_select
    - cw_items:fisherman_select
    - cw_items:gold_cog
    - cw_items:good
    - cw_items:home
    - cw_items:homehome
    - cw_items:hunter_select
    - cw_items:info
    - cw_items:inventory
    - cw_items:job02
    - cw_items:left_yellow
    - cw_items:mctown_quest_banner
    - cw_items:mctown_soap
    - cw_items:miner_select
    - cw_items:money_icon
    - cw_items:next
    - cw_items:ornamentsbag
    - cw_items:progress_green
    - cw_items:progress_red
    - cw_items:progress_yellow
    - cw_items:qiandao000
    - cw_items:qiandao111
    - cw_items:qiandao222
    - cw_items:qiandao333
    - cw_items:right_yellow
    - cw_items:scroll
    - cw_items:shang
    - cw_items:woodcutter_select
    - cw_items:xia
  off_hand:
    enabled: true
    icon: cw_items:off_hand_1_1
    name: off_hand
    items:
    - cw_items:off_hand_1_1
    - cw_items:off_hand_1_10
    - cw_items:off_hand_1_11
    - cw_items:off_hand_1_12
    - cw_items:off_hand_1_13
    - cw_items:off_hand_1_14
    - cw_items:off_hand_1_2
    - cw_items:off_hand_1_3
    - cw_items:off_hand_1_4
    - cw_items:off_hand_1_5
    - cw_items:off_hand_1_6
    - cw_items:off_hand_1_7
    - cw_items:off_hand_1_8
    - cw_items:off_hand_1_9
    - cw_items:off_hand_2_1
    - cw_items:off_hand_2_2
    - cw_items:off_hand_2_3
    - cw_items:off_hand_2_4
    - cw_items:off_hand_2_5
    - cw_items:off_hand_2_6
    - cw_items:off_hand_2_7
    - cw_items:off_hand_3_1
    - cw_items:off_hand_3_10
    - cw_items:off_hand_3_11
    - cw_items:off_hand_3_12
    - cw_items:off_hand_3_13
    - cw_items:off_hand_3_14
    - cw_items:off_hand_3_15
    - cw_items:off_hand_3_16
    - cw_items:off_hand_3_2
    - cw_items:off_hand_3_3
    - cw_items:off_hand_3_4
    - cw_items:off_hand_3_5
    - cw_items:off_hand_3_6
    - cw_items:off_hand_3_7
    - cw_items:off_hand_3_8
    - cw_items:off_hand_3_9
    - cw_items:off_hand_4_1
    - cw_items:off_hand_4_10
    - cw_items:off_hand_4_11
    - cw_items:off_hand_4_12
    - cw_items:off_hand_4_13
    - cw_items:off_hand_4_14
    - cw_items:off_hand_4_15
    - cw_items:off_hand_4_16
    - cw_items:off_hand_4_2
    - cw_items:off_hand_4_3
    - cw_items:off_hand_4_4
    - cw_items:off_hand_4_5
    - cw_items:off_hand_4_6
    - cw_items:off_hand_4_7
    - cw_items:off_hand_4_8
    - cw_items:off_hand_4_9
    - cw_items:off_hand_5_1
    - cw_items:off_hand_5_2
    - cw_items:off_hand_5_3
    - cw_items:off_hand_5_4
    - cw_items:off_hand_5_5
    - cw_items:off_hand_5_6
    - cw_items:off_hand_5_7
    - cw_items:off_hand_5_8
  ore:
    enabled: true
    icon: cw_items:adamantite
    name: ore
    items:
    - cw_items:adamantite
    - cw_items:adamantite_ingot
    - cw_items:aquamarine
    - cw_items:chlorophyte
    - cw_items:chlorophyte_ingot
    - cw_items:cobalt
    - cw_items:cobalt_ingot
    - cw_items:crimtane
    - cw_items:crimtane_ingot
    - cw_items:demonite
    - cw_items:demonite_ingot
    - cw_items:enderite
    - cw_items:enderite_ingot
    - cw_items:gem
    - cw_items:hallowed_ingot
    - cw_items:hellstone
    - cw_items:hellstone_ingot
    - cw_items:luminite
    - cw_items:luminite_ingot
    - cw_items:meteorite
    - cw_items:meteorite_ingot
    - cw_items:mythril
    - cw_items:mythril_ingot
    - cw_items:niter
    - cw_items:orichalcum
    - cw_items:orichalcum_ingot
    - cw_items:palladium
    - cw_items:palladium_ingot
    - cw_items:platinum
    - cw_items:platinum_ingot
    - cw_items:shroomite_ingot
    - cw_items:silver
    - cw_items:silver_ingot
    - cw_items:spectre_ingot
    - cw_items:titanium
    - cw_items:titanium_ingot
    - cw_items:tungsten
    - cw_items:tungsten_ingot
  ui:
    enabled: true
    icon: cw_items:b0
    name: ui
    items:
    - cw_items:b0
    - cw_items:b4
    - cw_items:ui_tp_1
    - cw_items:ui_tp_2
