info:
  namespace: cw_status
items:
  player_head_gui_size_1:
    enabled: true
    display_name: Head 1x1 GUI
    resource:
      generate: false
      model_path: items/player_head_gui_size_1
      material: PLAYER_HEAD
  player_head_gui_size_4:
    enabled: true
    display_name: Big Head 2x2 GUI
    resource:
      generate: false
      model_path: items/player_head_gui_size_4
      material: PLAYER_HEAD
  player_head_block_size_item_frame:
    enabled: true
    display_name: Head ItemFrame size
    resource:
      generate: false
      model_path: items/player_head_block_size_item_frame
      material: PLAYER_HEAD
  player_head_hand_size_2:
    enabled: true
    display_name: Big Head
    resource:
      generate: false
      model_path: items/player_head_hand_size_2
      material: PLAYER_HEAD
