# 自动生成的分类配置文件
# 生成工具: create_items.py

info:
  namespace: cw_made_tool
categories:
  sword:
    enabled: true
    icon: cw_made_tool:adamantite_sword
    name: sword
    items:
    - cw_made_tool:adamantite_sword
    - cw_made_tool:arkhalis
    - cw_made_tool:ash_wood_sword
    - cw_made_tool:beam_sword
    - cw_made_tool:bee_keeper
    - cw_made_tool:bladetongue
    - cw_made_tool:blade_of_grass
    - cw_made_tool:bloody_machete
    - cw_made_tool:blood_butcherer
    - cw_made_tool:bone_sword
    - cw_made_tool:boreal_wood_sword
    - cw_made_tool:brand_of_the_inferno
    - cw_made_tool:breaker_blade
    - cw_made_tool:cactus_sword
    - cw_made_tool:candy_cane_sword
    - cw_made_tool:chlorophyte_claymore
    - cw_made_tool:chlorophyte_saber
    - cw_made_tool:christmas_tree_sword
    - cw_made_tool:cobalt_sword
    - cw_made_tool:copper_broadsword
    - cw_made_tool:cutlass
    - cw_made_tool:death_sickle
    - cw_made_tool:durendal
    - cw_made_tool:ebonwood_sword
    - cw_made_tool:enchanted_sword
    - cw_made_tool:excalibur
    - cw_made_tool:exotic_scimitar
    - cw_made_tool:falcon_blade
    - cw_made_tool:first_fractal
    - cw_made_tool:flying_dragon
    - cw_made_tool:flymeal
    - cw_made_tool:frostbrand
    - cw_made_tool:gladius
    - cw_made_tool:gold_broadsword
    - cw_made_tool:hallowed_jousting_lance
    - cw_made_tool:icemourne
    - cw_made_tool:ice_blade
    - cw_made_tool:ice_sickle
    - cw_made_tool:influx_waver
    - cw_made_tool:iron_broadsword
    - cw_made_tool:jousting_lance
    - cw_made_tool:katana
    - cw_made_tool:lead_broadsword
    - cw_made_tool:light_bane
    - cw_made_tool:meowmere
    - cw_made_tool:muramasa
    - cw_made_tool:mythril_sword
    - cw_made_tool:night_edge
    - cw_made_tool:orichalcum_sword
    - cw_made_tool:palladium_sword
    - cw_made_tool:pearlwood_sword
    - cw_made_tool:platinum_broadsword
    - cw_made_tool:psycho_knife
    - cw_made_tool:rich_mahogany_sword
    - cw_made_tool:scythe
    - cw_made_tool:seedler
    - cw_made_tool:silver_broadsword
    - cw_made_tool:sky_fracture
    - cw_made_tool:soul_scythe
    - cw_made_tool:starfury
    - cw_made_tool:starlight
    - cw_made_tool:star_wrath
    - cw_made_tool:terragrim
    - cw_made_tool:terraprisma
    - cw_made_tool:terra_blade
    - cw_made_tool:the_horseman_blade
    - cw_made_tool:tin_broadsword
    - cw_made_tool:titanium_sword
    - cw_made_tool:tizona
    - cw_made_tool:true_excalibur
    - cw_made_tool:true_night_edge
    - cw_made_tool:tungsten_broadsword
    - cw_made_tool:volcano
    - cw_made_tool:wooden_sword
    - cw_made_tool:zenith
    - cw_made_tool:zombie_arm
