# 自动生成的分类配置文件
info:
  namespace: cw_made_tool
categories:
  diamond_shovel:
    enabled: true
    icon: cw_made_tool:enderite_shovel
    name: no_model_diamond_shovel
    items:
    - cw_made_tool:enderite_shovel
    - cw_made_tool:warden_shovel
