# 自动生成的物品配置文件
info:
  namespace: cw_armor
equipments:
  ar1:
    type: armor
    layer_1: armor/ar1/layer_1
    layer_2: armor/ar1/layer_2
items:
  ar1_boots:
    name: ar1_boots
    resource:
      generate: true
      texture: items/ar1/boots.png
      material: NETHERITE_boots
    equipment:
      id: cw_armor:ar1
  ar1_chestplate:
    name: ar1_chestplate
    resource:
      generate: true
      texture: items/ar1/chestplate.png
      material: NETHERITE_chestplate
    equipment:
      id: cw_armor:ar1
  ar1_helmet:
    name: ar1_helmet
    resource:
      generate: true
      texture: items/ar1/helmet.png
      material: NETHERITE_helmet
    equipment:
      id: cw_armor:ar1
  ar1_leggings:
    name: ar1_leggings
    resource:
      generate: true
      texture: items/ar1/leggings.png
      material: NETHERITE_leggings
    equipment:
      id: cw_armor:ar1
